---

- name: Set broker id dynamically
  set_fact:
    broker_id: "{{ (hostvars[inventory_hostname]['tags']['Name'] | regex_search('[0-9]+$') | int) - 1 }}"

- name: Create Kafka log directory
  file:
    path: "/var/lib/kafka-logs-{{ broker_id }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  become: yes

- name: Copy Kafka server.properties
  template:
    src: server.properties.j2
    dest: "{{ kafka_install_dir }}/config/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
  notify: Restart Kafka

- name: Copy Kafka systemd service
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    mode: '0644'
  become: yes
  notify:
    - Reload Systemd
    - Restart Kafka
