#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/kafka


- name: Install Kafka
  import_tasks: install.yml

- name: Configure Kafka
  import_tasks: configure.yml

- name: Configure ZooKeeper
  import_tasks: zookeeper.yml

- name: Wait for ZooKeeper to be ready before starting Kafka
  wait_for:
    host: "{{ hostvars[inventory_hostname]['private_ip_address'] }}"
    port: 2181
    delay: 5
    timeout: 120
  when: broker_id | int == 0

- name: Enable and Start Kafka
  systemd:
    name: kafka
    enabled: yes
    state: started
  become: yes
