---
# ZooKeeper runs only on broker-1

- name: Copy ZooKeeper systemd service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: '0644'
  become: yes
  when: broker_id | int == 0


- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  when: broker_id | int == 0


- name: Enable ZooKeeper
  systemd:
    name: zookeeper
    enabled: yes
  become: yes
  when: broker_id | int == 0


- name: Start ZooKeeper
  systemd:
    name: zookeeper
    state: started
  become: yes
  when: broker_id | int == 0


- name: Wait for ZooKeeper port 2181
  wait_for:
    host: "{{ hostvars[inventory_hostname]['private_ip_address'] }}"
    port: 2181
    delay: 5
    timeout: 120
  when: broker_id | int == 0
